//! Turns reviewed knowledge into the files of `.atlas/`.
//!
//! Two kinds of file, never mixed:
//! - **Generated** (`project.yaml`, `knowledge/findings.yaml`, `context/{architecture,stack,
//!   conventions,testing}.md`): written by Atlas from findings, each statement saying whether it
//!   is a fact, an inference or the user's word. Replaced on update, after the user reviewed the
//!   diff and with a backup.
//! - **User-owned** (`context/{business,constraints,decisions}.md`): the user's words. Atlas
//!   writes them only when they do not exist yet or when the user changed them in the review,
//!   and never rewrites a file whose format it cannot reproduce without losing text.

use std::fmt::Write;

use super::knowledge::{
    parse_body_file, parse_business, render_body_file, render_business, BUSINESS_FILE,
    CONSTRAINTS_FILE, DECISIONS_FILE,
};
use super::manifest::{render_knowledge, render_manifest};
use super::secrets::redact_secrets;
use crate::application::errors::AppError;
use crate::domain::harness::{
    Confidence, Finding, FindingCategory, HarnessFile, HarnessKnowledge, HarnessManifest, Origin,
    UserKnowledge,
};

const BANNER: &str = "<!-- Generated by Atlas from knowledge/findings.yaml. Your own words go in \
business.md, constraints.md and decisions.md; changes made here are replaced on update (a backup \
is kept). -->\n\n";

/// The folders of a Harness that are the project's to fill. Atlas only makes sure they exist.
const PLACEHOLDER_DIRS: &[&str] = &["agents", "workflows", "policies", "memory"];

/// The generated files. `effective` is `knowledge.findings` with the user's choices applied.
///
/// # Errors
///
/// `HarnessGenerationFailed` if the manifest or knowledge cannot be serialised.
pub fn generate(
    manifest: &HarnessManifest,
    knowledge: &HarnessKnowledge,
    effective: &[Finding],
) -> Result<Vec<HarnessFile>, AppError> {
    let generated = |path: &str, content: String| HarnessFile {
        path: path.to_owned(),
        content: format!("{BANNER}{content}"),
        keep_if_exists: false,
    };
    let mut files = vec![
        HarnessFile {
            path: "project.yaml".to_owned(),
            content: render_manifest(manifest)?,
            keep_if_exists: false,
        },
        HarnessFile {
            path: "knowledge/findings.yaml".to_owned(),
            content: render_knowledge(knowledge)?,
            keep_if_exists: false,
        },
        generated("context/architecture.md", architecture(effective)),
        generated("context/stack.md", stack(effective)),
        generated("context/conventions.md", conventions(effective)),
        generated("context/testing.md", testing(effective)),
    ];
    for dir in PLACEHOLDER_DIRS {
        files.push(HarnessFile {
            path: format!("{dir}/.gitkeep"),
            content: String::new(),
            keep_if_exists: true,
        });
    }
    Ok(files)
}

/// What is in the user's files now (`None`: the file does not exist).
#[derive(Debug, Default, Clone)]
pub struct ExistingUserFiles {
    pub business: Option<String>,
    pub constraints: Option<String>,
    pub decisions: Option<String>,
}

/// What the user's files hold now, as knowledge, and the files that cannot be read as such.
pub fn read_user_files(existing: &ExistingUserFiles) -> (UserKnowledge, Vec<String>) {
    let mut user = UserKnowledge::default();
    let mut unmanaged = Vec::new();
    if let Some(text) = &existing.business {
        match parse_business(text) {
            Some(parsed) => {
                user.purpose = parsed.purpose;
                user.users = parsed.users;
                user.concepts = parsed.concepts;
                user.business_rules = parsed.business_rules;
            }
            None => unmanaged.push(BUSINESS_FILE.to_owned()),
        }
    }
    if let Some(text) = &existing.constraints {
        user.constraints = parse_body_file(text);
    }
    if let Some(text) = &existing.decisions {
        user.decisions = parse_body_file(text);
    }
    (user, unmanaged)
}

/// The user's files to write for `wanted`, and those left alone.
///
/// A field the user left empty keeps what the file already says: emptying a field is done in
/// the file itself, never as a side effect of an update. Text that looks like a secret is
/// removed before it is written.
pub fn user_files(
    existing: &ExistingUserFiles,
    wanted: &UserKnowledge,
) -> (Vec<HarnessFile>, Vec<String>) {
    let (current, unmanaged) = read_user_files(existing);
    let pick = |new: &str, old: &str| {
        let new = redact_secrets(new.trim()).0;
        if new.is_empty() {
            old.to_owned()
        } else {
            new
        }
    };
    let merged = UserKnowledge {
        purpose: pick(&wanted.purpose, &current.purpose),
        users: pick(&wanted.users, &current.users),
        concepts: pick(&wanted.concepts, &current.concepts),
        business_rules: pick(&wanted.business_rules, &current.business_rules),
        constraints: pick(&wanted.constraints, &current.constraints),
        decisions: pick(&wanted.decisions, &current.decisions),
    };
    let mut files = Vec::new();
    let mut left = unmanaged.clone();
    let mut push = |path: &str, existing: &Option<String>, same: bool, content: String| {
        if existing.is_none() || !same {
            files.push(HarnessFile {
                path: path.to_owned(),
                content,
                keep_if_exists: false,
            });
        }
    };
    if existing.business.is_none() || !unmanaged.iter().any(|p| p == BUSINESS_FILE) {
        let same = merged.purpose == current.purpose
            && merged.users == current.users
            && merged.concepts == current.concepts
            && merged.business_rules == current.business_rules;
        push(
            BUSINESS_FILE,
            &existing.business,
            same,
            render_business(&merged),
        );
    }
    push(
        CONSTRAINTS_FILE,
        &existing.constraints,
        merged.constraints == current.constraints,
        render_body_file("Constraints", &merged.constraints),
    );
    push(
        DECISIONS_FILE,
        &existing.decisions,
        merged.decisions == current.decisions,
        render_body_file("Decisions", &merged.decisions),
    );
    left.sort();
    (files, left)
}

fn sources(f: &Finding) -> String {
    let mut list: Vec<String> = f
        .evidence
        .iter()
        .take(4)
        .map(|e| match &e.field {
            Some(field) if !field.is_empty() => format!("{} → {field}", e.source),
            _ => e.source.clone(),
        })
        .collect();
    if f.evidence.len() > 4 {
        list.push(format!("+{} more", f.evidence.len() - 4));
    }
    list.join(", ")
}

fn provenance(f: &Finding) -> String {
    match f.origin {
        Origin::Fact => format!("fact, from {}", sources(f)),
        Origin::Inference => format!(
            "inference, {} confidence, from {}",
            match f.confidence {
                Confidence::High => "high",
                Confidence::Medium => "medium",
                Confidence::Low => "low",
            },
            sources(f)
        ),
        Origin::UserConfirmed => "inference confirmed by the user".to_owned(),
        Origin::UserCorrected => "corrected by the user".to_owned(),
        Origin::Generated => "generated by Atlas, not from evidence".to_owned(),
    }
}

fn bullet(f: &Finding) -> String {
    let mut line = format!("- {} ({})\n", f.label, provenance(f));
    if matches!(f.origin, Origin::Inference | Origin::UserConfirmed) {
        if let Some(reason) = &f.reason {
            let _ = writeln!(line, "  - Why: {reason}");
        }
    }
    line
}

/// Prose the AI wrote for a whole file: shown as text, not as a bullet.
fn is_narrative(f: &Finding) -> bool {
    f.by_model
        && matches!(
            (f.category, f.key.as_str()),
            (FindingCategory::Architecture, "overview")
                | (FindingCategory::Convention, "practices")
                | (FindingCategory::Testing, "guidelines")
        )
}

fn narrative(findings: &[Finding], category: FindingCategory, key: &str) -> Option<String> {
    findings
        .iter()
        .find(|f| is_narrative(f) && f.category == category && f.key == key)
        .map(|f| format!("{}\n\n_{}_\n\n", f.value, provenance(f)))
}

fn section(findings: &[Finding], title: &str, category: FindingCategory) -> String {
    let items: String = findings
        .iter()
        .filter(|f| f.category == category && !is_narrative(f))
        .map(bullet)
        .collect();
    if items.is_empty() {
        String::new()
    } else {
        format!("## {title}\n\n{items}\n")
    }
}

fn stack(findings: &[Finding]) -> String {
    let body: String = [
        ("Languages", FindingCategory::Language),
        ("Frameworks", FindingCategory::Framework),
        ("Runtimes", FindingCategory::Runtime),
        ("Package managers", FindingCategory::PackageManager),
        ("Key dependencies", FindingCategory::Dependency),
        ("Databases", FindingCategory::Database),
        ("Data access", FindingCategory::Data),
        ("Integrations", FindingCategory::Integration),
        ("Infrastructure", FindingCategory::Infrastructure),
        ("CI/CD", FindingCategory::Ci),
        ("Entry points", FindingCategory::EntryPoint),
        (
            "Build and run commands (observed in the project, never run by Atlas)",
            FindingCategory::Build,
        ),
        ("Repository", FindingCategory::Repository),
        ("Environment", FindingCategory::Environment),
    ]
    .iter()
    .map(|(title, category)| section(findings, title, *category))
    .collect();
    let body = if body.is_empty() {
        "No technologies were detected in this project.\n".to_owned()
    } else {
        body
    };
    format!("# Stack\n\nDetected by Atlas from the repository; each item says where it came from.\n\n{body}")
}

fn architecture(findings: &[Finding]) -> String {
    let story = narrative(findings, FindingCategory::Architecture, "overview");
    let patterns: Vec<&Finding> = findings
        .iter()
        .filter(|f| {
            f.category == FindingCategory::Architecture
                && f.origin != Origin::Generated
                && !is_narrative(f)
        })
        .collect();
    let overview = if patterns.is_empty() && story.is_some() {
        String::new()
    } else if patterns.is_empty() {
        "Architecture has not been explicitly documented, and nothing in the repository shows a \
         recognisable pattern. Atlas does not guess one.\n"
            .to_owned()
    } else {
        let mut text = String::from(
            "What Atlas noticed. Inferences are candidates, not established facts:\n\n",
        );
        for f in patterns {
            let wording = match f.origin {
                Origin::Inference => {
                    format!("Possible: {}", f.label)
                }
                _ => f.label.clone(),
            };
            let _ = writeln!(text, "- {wording} ({})", provenance(f));
            if let Some(reason) = &f.reason {
                let _ = writeln!(text, "  - Why: {reason}");
            }
        }
        text
    };
    let modules = section(findings, "Main Modules", FindingCategory::Module);
    let modules = if modules.is_empty() {
        "## Main Modules\n\nMain modules have not been documented or established.\n\n".to_owned()
    } else {
        modules
    };
    let overview = format!("{}{overview}", story.unwrap_or_default());
    format!(
        "# Architecture\n\n## Overview\n\n{overview}\n{modules}## Decisions to preserve\n\n\
         See decisions.md (written by the user).\n"
    )
}

/// How agents working in this project hand a plan to people. It is Atlas's own rule, not
/// something found in the repository, and it is stated here so every agent reads it.
const WORKING_AGREEMENTS: &str = "## Working agreements (Atlas)\n\n\
- **Plans are mandatory documents.** An agent that proposes or is asked for a plan, design or \
analysis before implementing must write it in full as Markdown in its message (Atlas shows it to \
the person, highlighted, with the notification) and, if it can create files, also save it as \
`docs/plans/<short-name>.md`.\n\
- A plan is approved by the person in Atlas before implementation starts; approval lets the agent \
continue in its isolated worktree and never applies anything to the project.\n";

fn conventions(findings: &[Finding]) -> String {
    let conventions = section(
        findings,
        "Observed conventions",
        FindingCategory::Convention,
    );
    let tooling = section(findings, "Detected tooling", FindingCategory::Tooling);
    let branch = findings
        .iter()
        .find(|f| f.id == "repository:current_branch")
        .map_or_else(
            || "Not documented.\n".to_owned(),
            |f| format!("Branch when analysed: {} ({}).\n", f.value, provenance(f)),
        );
    let practices = narrative(findings, FindingCategory::Convention, "practices")
        .map_or_else(String::new, |text| format!("## Practices\n\n{text}"));
    let none = if conventions.is_empty() && practices.is_empty() {
        "No conventions were established from the repository.\n\n"
    } else {
        ""
    };
    format!(
        "# Development Conventions\n\nOnly what was observed or read in the project's documents. Anything not listed is not known.\n\n\
         {none}{practices}{conventions}{tooling}## Git\n\n{branch}\n{WORKING_AGREEMENTS}"
    )
}

fn testing(findings: &[Finding]) -> String {
    let in_testing = |f: &&Finding| {
        f.category == FindingCategory::Testing
            || (f.category == FindingCategory::Build && f.key.starts_with("test_"))
            || f.key == "test_file_pattern"
    };
    let items: Vec<&Finding> = findings.iter().filter(in_testing).collect();
    let list = |keys: &[&str]| -> String {
        items
            .iter()
            .filter(|f| keys.contains(&f.key.as_str()))
            .map(|f| bullet(f))
            .collect()
    };
    let frameworks: String = items
        .iter()
        .filter(|f| {
            f.category == FindingCategory::Testing
                && ![
                    "guidelines",
                    "test_files",
                    "tests_directory",
                    "e2e_tests",
                    "integration_tests",
                    "unit_tests",
                    "coverage_config",
                ]
                .contains(&f.key.as_str())
        })
        .map(|f| bullet(f))
        .collect();
    let commands: String = items
        .iter()
        .filter(|f| f.category == FindingCategory::Build)
        .map(|f| bullet(f))
        .collect();
    let guidelines = narrative(findings, FindingCategory::Testing, "guidelines")
        .map_or_else(String::new, |text| format!("## Guidelines\n\n{text}"));
    let part = |title: &str, body: String, missing: &str| {
        format!(
            "## {title}\n\n{}\n\n",
            if body.is_empty() {
                format!("{missing}\n")
            } else {
                body
            }
        )
    };
    format!(
        "# Testing\n\nFramework installed, test files present, a test command and coverage \
         configuration are different facts; each is listed on its own.\n\n{guidelines}{}{}{}{}{}",
        part(
            "Frameworks detected",
            frameworks,
            "No test framework was detected."
        ),
        part(
            "Test files and conventions",
            list(&["test_files", "test_file_pattern", "tests_directory"]),
            "No test files were found."
        ),
        part(
            "Kinds of tests",
            list(&["unit_tests", "integration_tests", "e2e_tests"]),
            "No unit, integration or end-to-end test folders were found."
        ),
        part("Commands", commands, "No test command was found."),
        part(
            "Coverage",
            list(&["coverage_config"]),
            "No coverage configuration was found."
        ),
    )
}
