use tauri_build::{AppManifest, Attributes};

/// Every command the frontend may call must be listed here. Tauri then generates an
/// `allow-<command>` permission for it, and the command is unreachable from the webview
/// unless a capability in `capabilities/` grants that permission.
const COMMANDS: &[&str] = &[
    "get_app_info",
    "list_personalities",
    "create_personality",
    "update_personality",
    "delete_personality",
    "restore_default_personalities",
    "list_runtimes",
    "list_agents",
    "create_agent",
    "update_agent",
    "set_agent_result_contract",
    "delete_agent",
    "list_workspaces",
    "create_workspace",
    "update_workspace",
    "delete_workspace",
    "add_agent_to_workspace",
    "remove_agent_from_workspace",
    "get_project_context",
    "get_settings",
    "set_language",
    "select_workspace",
    "send_message",
    "list_messages",
    "list_executions",
    "get_agent_usage",
    "get_workspace_usage",
    "get_workspace_security",
    "get_agent_permissions",
    "set_agent_permission_profile",
    "list_pending_approvals",
    "resolve_approval",
    "get_execution_terminal",
    "execution_interrupt",
    "execution_terminate",
    "execution_terminal_input",
    "execution_terminal_resize",
    "list_execution_worktrees",
    "merge_execution",
    "analyze_project",
    "initialize_project",
    "get_project_harness",
    "refresh_project_harness",
    "preview_task_context",
    "list_workflows",
    "get_workflow",
    "list_workflow_templates",
    "select_workflow_template",
    "create_workflow",
    "create_workflow_from_template",
    "update_workflow",
    "delete_workflow",
    "validate_workflow",
    "start_workflow",
    "pause_workflow",
    "resume_workflow",
    "cancel_workflow",
    "answer_workflow_interaction",
    "list_pending_interactions",
    "get_workflow_execution",
    "list_workflow_executions",
    "get_workflow_changes",
    "get_workflow_diff",
    "apply_workflow_changes",
    "keep_workflow_changes",
    "discard_workflow_changes",
    "list_ides",
    "open_workflow_in_ide",
];

fn main() {
    tauri_build::try_build(Attributes::new().app_manifest(AppManifest::new().commands(COMMANDS)))
        .expect("failed to run tauri-build");
}
